
# This file is automatically generated, you probably don't want to edit this

nailqdaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "nailqdaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            product = NULL,
            panelist = NULL,
            attributes = NULL,
            introduction = "",
            model = "mistral-small3.2",
            showEvidence = FALSE,
            showPrompt = FALSE,
            generationRequest = "",
            reportPath = "",
            reportRequest = "", ...) {

            super$initialize(
                package="LacqueR",
                name="nailqda",
                requiresData=TRUE,
                ...)

            private$..product <- jmvcore::OptionVariable$new(
                "product",
                product,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..panelist <- jmvcore::OptionVariable$new(
                "panelist",
                panelist,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..attributes <- jmvcore::OptionVariables$new(
                "attributes",
                attributes,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..introduction <- jmvcore::OptionString$new(
                "introduction",
                introduction,
                hidden=TRUE,
                default="")
            private$..model <- jmvcore::OptionString$new(
                "model",
                model,
                default="mistral-small3.2")
            private$..showEvidence <- jmvcore::OptionBool$new(
                "showEvidence",
                showEvidence,
                default=FALSE)
            private$..showPrompt <- jmvcore::OptionBool$new(
                "showPrompt",
                showPrompt,
                default=FALSE)
            private$..generationRequest <- jmvcore::OptionString$new(
                "generationRequest",
                generationRequest,
                hidden=TRUE,
                default="")
            private$..reportPath <- jmvcore::OptionString$new(
                "reportPath",
                reportPath,
                default="")
            private$..reportRequest <- jmvcore::OptionString$new(
                "reportRequest",
                reportRequest,
                hidden=TRUE,
                default="")

            self$.addOption(private$..product)
            self$.addOption(private$..panelist)
            self$.addOption(private$..attributes)
            self$.addOption(private$..introduction)
            self$.addOption(private$..model)
            self$.addOption(private$..showEvidence)
            self$.addOption(private$..showPrompt)
            self$.addOption(private$..generationRequest)
            self$.addOption(private$..reportPath)
            self$.addOption(private$..reportRequest)
        }),
    active = list(
        product = function() private$..product$value,
        panelist = function() private$..panelist$value,
        attributes = function() private$..attributes$value,
        introduction = function() private$..introduction$value,
        model = function() private$..model$value,
        showEvidence = function() private$..showEvidence$value,
        showPrompt = function() private$..showPrompt$value,
        generationRequest = function() private$..generationRequest$value,
        reportPath = function() private$..reportPath$value,
        reportRequest = function() private$..reportRequest$value),
    private = list(
        ..product = NA,
        ..panelist = NA,
        ..attributes = NA,
        ..introduction = NA,
        ..model = NA,
        ..showEvidence = NA,
        ..showPrompt = NA,
        ..generationRequest = NA,
        ..reportPath = NA,
        ..reportRequest = NA)
)

nailqdaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "nailqdaResults",
    inherit = jmvcore::Group,
    active = list(
        generationState = function() private$.items[["generationState"]],
        reportState = function() private$.items[["reportState"]],
        status = function() private$.items[["status"]],
        response = function() private$.items[["response"]],
        evidence = function() private$.items[["evidence"]],
        prompt = function() private$.items[["prompt"]],
        reportStatus = function() private$.items[["reportStatus"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="AI-assisted QDA")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="generationState",
                visible=FALSE,
                clearWith=list()))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="reportState",
                visible=FALSE,
                clearWith=list()))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="status",
                title="Interpretation status",
                clearWith=list(
                    "product",
                    "panelist",
                    "attributes",
                    "introduction",
                    "model",
                    "generationRequest")))
            self$add(jmvcore::Html$new(
                options=options,
                name="response",
                title="Product interpretation",
                clearWith=list(
                    "product",
                    "panelist",
                    "attributes",
                    "introduction",
                    "model",
                    "generationRequest")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="evidence",
                title="Supporting statistical evidence",
                visible="(showEvidence)",
                clearWith=list(
                    "product",
                    "panelist",
                    "attributes",
                    "introduction")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="prompt",
                title="Generation prompt",
                visible="(showPrompt)",
                clearWith=list(
                    "product",
                    "panelist",
                    "attributes",
                    "introduction")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="reportStatus",
                title="PowerPoint report status",
                clearWith=list(
                    "reportRequest")))}))

nailqdaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "nailqdaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "LacqueR",
                name = "nailqda",
                version = c(1,0,0),
                options = options,
                results = nailqdaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' AI-assisted QDA
#'
#' 
#' @param data .
#' @param product .
#' @param panelist .
#' @param attributes .
#' @param introduction .
#' @param model .
#' @param showEvidence .
#' @param showPrompt .
#' @param generationRequest .
#' @param reportPath .
#' @param reportRequest .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$generationState} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$reportState} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$status} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$response} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$evidence} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$prompt} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$reportStatus} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
nailqda <- function(
    data,
    product,
    panelist,
    attributes,
    introduction = "",
    model = "mistral-small3.2",
    showEvidence = FALSE,
    showPrompt = FALSE,
    generationRequest = "",
    reportPath = "",
    reportRequest = "") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("nailqda requires jmvcore to be installed (restart may be required)")

    if ( ! missing(product)) product <- jmvcore::resolveQuo(jmvcore::enquo(product))
    if ( ! missing(panelist)) panelist <- jmvcore::resolveQuo(jmvcore::enquo(panelist))
    if ( ! missing(attributes)) attributes <- jmvcore::resolveQuo(jmvcore::enquo(attributes))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(product), product, NULL),
            `if`( ! missing(panelist), panelist, NULL),
            `if`( ! missing(attributes), attributes, NULL))

    for (v in product) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in panelist) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- nailqdaOptions$new(
        product = product,
        panelist = panelist,
        attributes = attributes,
        introduction = introduction,
        model = model,
        showEvidence = showEvidence,
        showPrompt = showPrompt,
        generationRequest = generationRequest,
        reportPath = reportPath,
        reportRequest = reportRequest)

    analysis <- nailqdaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

